= How To: Bluetooth control of Raspberry Pi

A simple daemon which accepts commands from a paired bluetooth client.

== Install Python's bluez package on your Pi and PC
-----------------------------------------------------
$ sudo apt-get install python-bluez bluez python-gobject python-dbus python-daemon
-----------------------------------------------------

== Discover the hciX address of your Pi
-----------------------------------------------------
$ hcitool dev

Devices:
	hci0	xx:xx:xx:xx:xx:xx
-----------------------------------------------------

== Discover the address of your phone/laptop
* Make sure Bluetooth is enabled on the phone/laptop. 
* Make sure Bluetooth on your phone/laptop is set to visible.
* On an Android phone, go to settings->Bluetooth. Turn on visibility. The device only remains visible for a short time.

-----------------------------------------------------
./finddevice.py
-----------------------------------------------------

== Add phone/laptop bluetooth as trusted to the Pi
* Temporarily:

-----------------------------------------------------
bluez-simple-agent hci# xx:xx:xx:xx:xx:xx
-----------------------------------------------------

* Permanently:

-----------------------------------------------------
sudo bluez-test-device trusted xx:xx:xx:xx:xx:xx yes
-----------------------------------------------------

== Start Daemon on Pi
* Daemon implements start/stop/restart. To start daemon on Pi, type:

-----------------------------------------------------
./daemon-rxcmd.py start
-----------------------------------------------------

== Add an init script

== Send commands from your laptop to the daemon:
-----------------------------------------------------
./rxcmd.py 
-----------------------------------------------------
Pi screen should read:
-----------------------------------------------------
Accepted connection from  ('xx:xx:xx:xx:xx:xx', 1)
received [hello!!]
-----------------------------------------------------
You can now enter commands

== References

* http://www.gavinj.net/2012/06/building-python-daemon-process.html
* http://blog.scphillips.com/posts/2013/07/getting-a-python-script-to-run-in-the-background-as-a-service-on-boot/
* 
